=pod

=encoding UTF-8

=head1 NAME

PONAPI - Perl implementation of {JSON:API} (http://jsonapi.org) v1.0

=head1 DESCRIPTION

C<PONAPI::Server> is a small plack server that implements the
L<{json:api}|http://jsonapi.org> specification.

C<PONAPI::Client> is a L<{JSON:API}|http://jsonapi.org> compliant client;
it should be able to communicate with any API-compliant service

=head1 AUTHORS

=over 4

=item *

Mickey Nasriachi <mickey@cpan.org>

=item *

Stevan Little <stevan@cpan.org>

=item *

Brian Fraser <hugmeir@cpan.org>

=back

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2016 by Mickey Nasriachi, Stevan Little, Brian Fraser.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut
