=pod

=encoding UTF-8

=head1 NAME

PONAPI - Perl implementation of L<{json:api}|http://jsonapi.org> v1.0

=head1 DESCRIPTION

L<Server|https://github.com/mickeyn/PONAPI/tree/master/Server> is a Perl
implementation of the L<{json:api}|http://jsonapi.org> specification;
it should be able to communicate with any API-compliant client.

L<Client|https://github.com/mickeyn/PONAPI/tree/master/Client> is a Perl
implementation of a L<{json:api}|http://jsonapi.org> compliant client;
it should be able to communicate with any API-compliant service.

=head1 AUTHORS

=over 4

=item *

Mickey Nasriachi <mickey@cpan.org>

=item *

Stevan Little <stevan@cpan.org>

=item *

Brian Fraser <hugmeir@cpan.org>

=back

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2016 by Mickey Nasriachi, Stevan Little, Brian Fraser.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut
