=pod

=encoding UTF-8

=head1 NAME

PONAPI::Tools - PONAPI-Tools - {json:api} document building tools

=head1 VERSION

version 0.001001

=head1 DESCRIPTION

Various tools for building {json:api} compatiable documents.

Used by L<PONAPI::Server>

For information about creating documents, see: L<PONAPI::Document>

=head1 AUTHORS

=over 4

=item *

Mickey Nasriachi <mickey@cpan.org>

=item *

Stevan Little <stevan@cpan.org>

=item *

Brian Fraser <hugmeir@cpan.org>

=back

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2016 by Mickey Nasriachi, Stevan Little, Brian Fraser.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut
